//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaukaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptOrder_Product
    {
        public int ID { get; set; }
        public int OrderNum { get; set; }
        public int Quantity { get; set; }
        public int WarehouseID { get; set; }
        public int ProductNumber { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ReceiptOrder ReceiptOrder { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
