//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaukaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReceiptOrder()
        {
            this.ReceiptOrder_Product = new HashSet<ReceiptOrder_Product>();
        }
    
        public int OrderNum { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string DeliveryContract { get; set; }
        public int ProviderID { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Provider Provider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptOrder_Product> ReceiptOrder_Product { get; set; }
    }
}
